### ISSUE TITLE
目前正常登录,但是chatGpt标签提示Access denied

### ISSUE THREAD

**Issue by monkeyKinn** [dromara/ChatGPT#100]
(前置验证:  在本机代理下Chrome浏览器能够访问chatgpt并发送数据)

![image](https://user-images.githubusercontent.com/46397336/223955726-71ec1db0-37ee-4618-b24e-c45518603586.png)

步骤:

- 1.插件设置页已经用账号登录(为什么我用google账号也能登录成功并且成功更新token)

- 2.也配置了本机代理
![image](https://user-images.githubusercontent.com/46397336/223955530-5ee577ee-c386-4cec-a591-de1f00489417.png)
- 3.出现的问题:

1.chatGpt标签提示Access denied

`Access denied
Error code 1020
You do not have access to chatgpt.duti.tech.
The site owner may have set restrictions that prevent you from accessing the site.
 
Error details
   
Provide the site owner this information.
 
I got an error when visiting chatgpt.duti.tech/api/conversation.
Error code: 1020
Ray ID: 7a51a248f8519e56
Country: US
Data center: sjc05
IP: 140.99.149.35
Timestamp: 2023-03-09 07:34:10 UTC
Click to copy
 
Was this page helpful?  Yes   No 
Thank you for your feedback!`
![image](https://user-images.githubusercontent.com/46397336/223955229-96a8b109-ba08-4f37-8280-23471e50d4dc.png)

2.online chatgpt白屏

![image](https://user-images.githubusercontent.com/46397336/223955270-97003694-0507-4ebc-b4b1-3b2217198e9a.png)

**Comment by obiscr** [comment]
这就是之前说的 ，第三方服务不稳定的表现之一，目前只能等服务器的维护者修复。

**Comment by obiscr** [comment]
临时的替代方式是：先使用内置的在线ChatGPT，在线ChatGPT支持鼠标的内置指令。
