### ISSUE TITLE
GPT-3.5-Turbo格式

### ISSUE THREAD

**Issue by Saunak626** [dromara/ChatGPT#101]
目前从GPT-3.5-Turbo窗口复制出来的代码，带有前端代码，能否添加复制按钮呢（目前那个复制出来也有前端代码）？
并且目前的字体大小好像无法调整？是否能保留chatgpt原来的代码块风格？
![image](https://user-images.githubusercontent.com/34276206/224049799-ac31ac97-7991-4c5a-a3e2-847c39411b49.png)

**Comment by obiscr** [comment]
很抱歉，目前使用的组件在这方面不是很好处理这个问题。我会寻找其他的组件来解决这个问题。

**Comment by obiscr** [comment]
目前带有前段代码的问题已经修复。原有的代码块是markdown的。复制出来之后需要自己去掉markdown的一些格式字符。

**Comment by curtlun** [comment]
![image](https://user-images.githubusercontent.com/118433204/225491915-de268523-8e8a-4691-92c1-c8045649592c.png)

**Comment by curtlun** [comment]
求解
配置代理了还是不好使

**Comment by obiscr** [comment]
可能是第三方服务器的问题。不稳定，我这里也是如此
