### ISSUE TITLE
Reponse failure

### ISSUE THREAD

**Issue by lucasmd** [dromara/ChatGPT#102]
Hello,

i've just installed the application, copy paste Access token and then got  :

Response failure, cause: chatgpt.duti.tech: nodename nor servname provided, or not known, please try again.  Tips: if proxy is enabled, please check if the proxy server is working.

Any idea ?

**Comment by Liukang1002** [comment]
Response failure, cause: Remote host terminated the handshake, please try again.  Tips: if proxy is enabled, please check if the proxy server is working

I have the same problem

**Comment by obiscr** [comment]
This looks like a problem with a third party server. I'm sorry to say that this is not a problem that I can handle very well. I can only wait for the server maintainer to fix the problem.

The temporary solution I can give from my side is to use the plugin's built-in online ChatGPT for now.
