### ISSUE TITLE
How use proxy with auth username:password?

### ISSUE THREAD

**Issue by max4com** [dromara/ChatGPT#103]
Hello,
Is it possible to use proxy with auntification?

**Comment by max4com** [comment]
Hello,
Is it possible to use proxy with auntification?

**Comment by obiscr** [comment]
Sorry, this feature may be supported in the next release.

But I have a difficulty now, I don't have a similar proxy server and I have no way to test it after I'm done.

**Comment by obiscr** [comment]
The latest version 2.1.8 has been suooprted it. Please see [release note](https://chatgpt.en.obiscr.com/release/2.1.8/#support-proxy-authentication)
