### ISSUE TITLE
新版UI界面无法使用

### ISSUE THREAD

**Issue by violets007** [dromara/ChatGPT#108]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/20490066/224480852-3991bc00-db8d-4222-b135-0cd584c320c3.png">

**Comment by obiscr** [comment]
This is a bug, duplicated with [#94](https://github.com/dromara/ChatGPT/issues/94), it will be fixed in the next version update.

For the time being, you can refer to here to solve：https://github.com/dromara/ChatGPT/issues/94#issuecomment-1463670647
