### ISSUE TITLE
Self host the chatgpt proxy

### ISSUE THREAD

**Issue by Alexr03** [dromara/ChatGPT#110]
~~Would it be possible to self host the site behind https://chatgpt.duti.tech/api/conversation so we can use it without going through this proxy.~~

I believe its this https://github.com/acheong08/ChatGPT-Proxy-V1.

**Comment by obiscr** [comment]
This approach is possible as long as you have your own service. You can configure a custom URL in the OpenAI - ChatGPT.

> I believe its this https://github.com/acheong08/ChatGPT-Proxy-V1.

The original author said that this seems to have been closed by OpenAI.
