### ISSUE TITLE
封号

### ISSUE THREAD

**Issue by pyQianYi** [dromara/ChatGPT#113]
用key的方式，可能会被封号。我用了两个账号的key，两个账号都被封了。
Hi there,

After a thorough investigation, we have determined that you or a member of your organization are using the OpenAI API in ways that violate our policies.

Due to this breach we are halting access to the API immediately for the organization Personal. Common reasons for breach include violations of our [usage policies] or accessing the API from an [unsupported location]. You may also wish to review our [Terms of Use]
If you believe this is in error and would like to appeal, please contact us through our [help center]. We will review appeals within one business day and will contact you if we reinstate access to the API.

Best,
The OpenAI team
![image](https://user-images.githubusercontent.com/57526688/224606276-681952fb-9fd9-408b-835a-33087d5be044.png)

**Comment by obiscr** [comment]
代码是开源的，所做的操作，完全是透明化的。请求的URL，携带的参数等是官方提供的demo保持一致的。

因此对于您的观点，我不认同。至少目前我还没有收到反馈说，因为插件导致封号的案例。

**Comment by pyQianYi** [comment]
我是在局域网内配置了代理服务器，系统代理模式是PAC代理模式，使用的站点是日本的，在此之前一直是通过官网的使用，期间没有发生任何问题；按照文档中的配置去配置了http代理的IP和端口，然后插件可以正常使用，用了10分钟左右后就不行了，返回错误，不久后就收到了openai的邮件；

**Comment by pyQianYi** [comment]
![image](https://user-images.githubusercontent.com/57526688/224619322-93d9cb71-8454-48b2-a924-6a9cc820bf6d.png)
![image](https://user-images.githubusercontent.com/57526688/224619378-fb7daedb-8463-4a5b-a453-6ad738658976.png)
我的环境和配置主要就是这样的，平时使用chatGPT是通过谷歌浏览器的[SwitchyOmega]插件代理到内网服务器访问的

**Comment by obiscr** [comment]
很遗。但这依然不是直接的证据，我自己上百个账号都没问题。能够正常使用。没有一例封号的情况。

**Comment by obiscr** [comment]
@pyQianYi 你好，可以发一下你的邮箱吗？

**Comment by pyQianYi** [comment]
956782395@qq.com

**Comment by pyQianYi** [comment]
> @pyQianYi 你好，可以发一下你的邮箱吗？

956782395@qq.com
