### ISSUE TITLE
PKIX path building failed

### ISSUE THREAD

**Issue by 0815pascal** [dromara/ChatGPT#116]
Since one of the most recent plugin-updates I'm receiving an error-message when trying to use GPT-3.5-Turbo: 

```
GPT 3.5 Turbo Request failure, cause: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: 
unable to find valid certification path to requested target
```

Now I'm not sure if this is related due to some configuration problems on my side (I haven't changed anything recently though and before it worked) or if it's related to the updates. Reporting it here to be sure though. And thanks a lot by the way for bringing ChatGPT to IntelliJ :)

**Comment by obiscr** [comment]
Thanks for the feedback. First time I've encountered this issue. This looks like it is due to a problem with the OpenAI server.

At this moment, I am using it normally. Can you try changing the apiKey or changing the network environment and then request again to see if the error is still there?

**Comment by obiscr** [comment]
@NargiT Thank you very much for the solution.

**Comment by Khatib-Abbas** [comment]
> I was able to fix this by adding the certificate to the internal intellij jre
> 
> ```
> keytool -noprompt -keystore ~/.local/share/JetBrains/Toolbox/cacerts -import -trustcacerts -file /usr/local/share/ca-certificates/YOUR_CERT.crt -alias uniq name -storepass STORE_PASSWORD
> ```

Hi thank you this solution worked for me
