### ISSUE TITLE
After 2.1.6, Failed to authenticate with proxy

### ISSUE THREAD

**Issue by Jerrysmd** [dromara/ChatGPT#117]
Thanks to this convenient plug-in, it really improves my efficiency.

+ Problem: GTP 3.5 Turbo Request failure, Failed to authenticate with proxy.

![image](https://user-images.githubusercontent.com/25995001/225797928-7913a8b8-c413-452d-bea4-bf0379ff4d4a.png)

+ Version: After 2.1.6 (include 2.1.6). Before that works well.

+ Software: Same problem in latest Pycharm and IDEA.

+ Special info: my work have strict network limit. But in 2.1.5 plugin works well.

**Comment by Jerrysmd** [comment]
And I didn't find any clues from the commit and the code.

**Comment by obiscr** [comment]
Thanks for the feedback, can you give me a temporary proxy server address. If it is an extranet proxy. Because it is working fine on my end. I have no way to test it.

**Comment by obiscr** [comment]
Can you check the idea.log. would it be the problem: https://github.com/dromara/ChatGPT/issues/116

**Comment by obiscr** [comment]
This issue is out of date. Close for now!
