### ISSUE TITLE
chatgpt下发送消息后回复栏为空，但是点击复制后发现有回复

### ISSUE THREAD

**Issue by jsk2019** [dromara/ChatGPT#119]
![image](https://user-images.githubusercontent.com/50001656/226151908-dc3fea24-87cd-4a21-9860-921d61b09c87.png)

**Comment by obiscr** [comment]
感谢反馈，应该是UI刷新的问题，请问有稳定的复现步骤吗？

**Comment by obiscr** [comment]
这个问题已经过时。没有受到任何回复。
