### ISSUE TITLE
右键默认前缀能否改为中文

### ISSUE THREAD

**Issue by WJZhen** [dromara/ChatGPT#120]
![image](https://user-images.githubusercontent.com/46745276/226231181-2f0e2501-e09a-4100-b2dc-374ee4fcdc15.png)
默认的find bug和optimize的前缀文本为英文,能否修改为中文(影响gpt返回的结果语言)

**Comment by obiscr** [comment]
目前国际化有些问题，暂时还没处理（优先级相对不高）。
你可以在Custom Action添加中文，直接用Custom Actions 来解决这个问题。
可以达到同样的效果

![image](https://user-images.githubusercontent.com/28687074/226243142-c7d896f8-d76a-48cb-863c-3bf15537b143.png)
