### ISSUE TITLE
chatgpt account deactivated

### ISSUE THREAD

**Issue by Skyly119** [dromara/ChatGPT#124]
I filled out the ChatGPT api on this plugin yesterday and now my account has been deactivated, what exactly is the reason for this, and is there any way to find material to prove that I am using it properly?

**Comment by obiscr** [comment]
It is not clear what is willing to cause the account to be deactivated, I posted the announcement here before: https://github.com/dromara/ChatGPT/discussions/115

There are cases where some people have not used my plugin, but their accounts remain account disabled.

You can try to appeal. Get your account back.

You can find some useful information here: https://github.com/acheong08/ChatGPT/issues/1158
