### ISSUE TITLE
no result

### ISSUE THREAD

**Issue by beijJxy** [dromara/ChatGPT#125]
![image](https://user-images.githubusercontent.com/128446169/226823061-74afbfed-4afe-480e-80fe-3737847d9f04.png)

**Comment by obiscr** [comment]
Have you configured the API Key?

**Comment by beijJxy** [comment]
yes i configured  
![image](https://user-images.githubusercontent.com/128446169/227124316-15d21d0b-19f5-48bd-9eef-5adf96d73120.png)

**Comment by beijJxy** [comment]
by the way  i use ide is goland

**Comment by obiscr** [comment]
Can you provide me with your idea.log, it will help me to locate the problem?

**Comment by obiscr** [comment]
This issue is out of date.
