### ISSUE TITLE
希望添加右键解释代码功能

### ISSUE THREAD

**Issue by CrazyBunQnQ** [dromara/ChatGPT#126]
ChatGPT 解释代码的能力挺强的

对查看文档、看别人代码等操作很有帮助

希望能添加右键解释选中代码的功能

- 选中代码右键触发
- 读取当前文件类型(有时候直接粘给 gpt 它偶尔会识别成其他语言)
- 调 ChatGPT(使用 api 还是网页接口, 个人偏好 api, 是否要添加配置项)
- 显示结果，并有复制按钮

一个网页/翻译软件插件的参考图，貌似可供参考

![](https://user-images.githubusercontent.com/17765748/226827459-9b28786d-5b5b-437d-8c47-5009192b05a7.png)

![](https://user-images.githubusercontent.com/1206493/223200182-6a1d2a02-3fe0-4723-bdae-99d8b7212a33.gif)

**Comment by obiscr** [comment]
上面的这些，你可以使用[自定义前缀](https://chatgpt.cn.obiscr.com/settings/custom-prefix-settings/)来实现，配合快捷键的话，还是比较方便的。自定义前缀是一种比较通用的解决方案。至于翻译，可以参考下 Translation 插件。

**Comment by CrazyBunQnQ** [comment]
> 上面的这些，你可以使用[自定义前缀](https://chatgpt.cn.obiscr.com/settings/custom-prefix-settings/)来实现，配合快捷键的话，还是比较方便的。自定义前缀是一种比较通用的解决方案。至于翻译，可以参考下 Translation 插件。

原来如此，支持定义多个么~

**Comment by CrazyBunQnQ** [comment]
> 上面的这些，你可以使用[自定义前缀](https://chatgpt.cn.obiscr.com/settings/custom-prefix-settings/)来实现，配合快捷键的话，还是比较方便的。自定义前缀是一种比较通用的解决方案。至于翻译，可以参考下 Translation 插件。

666 给力~
