### ISSUE TITLE
受限于国内网络，如何使用自有的API接口

### ISSUE THREAD

**Issue by yufeiyohi** [dromara/ChatGPT#127]
由于openai限制了国内网络，在不翻墙的情况下无法访问到api接口，请问如果使用自建的api接口，这样就不用再挂梯子了。

**Comment by obiscr** [comment]
如果只是GPT 3.5 Turbo 的 API的话，nginx网络转发应该可以，这是一个思路。具体的需要您自己解决。我没法提供更多的帮助。

**Comment by yufeiyohi** [comment]
接口我已经作完了，举个例子，原本程序调用api是通过https://api.openai.com/v1/completions/，现在我自己作好了接口比如https://api.test.com/v1/completions，怎么能让你的程序直接调用我，新的接口地址呢？你的程序内有留换的地方吗？

**Comment by obiscr** [comment]
我明白你的意思了，这个可以下个版本新增一下。暂时没有预留的接口配置位置。

**Comment by MeditatorV** [comment]
这个问题也是我想问的，我使用云函数，部署了自己API，希望这功能可以迭代出来

**Comment by obiscr** [comment]
在 [2.1.8](https://chatgpt.en.obiscr.com/release/2.1.8/#support-proxy-authentication) 版本，已经支持自定义 自有的url。但是配置比较麻烦。在你的电脑上搜索：**ChatGPTSettingsPlugin.xml**， 修改里面的 gpt35TurboUrl  的值为你自己的URL。

> 注意，**ChatGPTSettingsPlugin.xml* 这个文件可能会有多个，每个ide都有自己的这个配置文件。你使用哪个ide，就修改那个ide的就行。

**Comment by yufeiyohi** [comment]
能否把这个配置作个plug-in的界面里面，我手动修改好这个文件后ChatGPTSettingsPlugin.xml，在Pycharm当中打开你这个插件后，修改的配置会自动去掉，请问这个怎么破？

**Comment by yufeiyohi** [comment]
![image](https://user-images.githubusercontent.com/12806645/228149350-5c1b51fb-60d7-4f98-8171-b81bb7efab0c.png)

**Comment by yufeiyohi** [comment]
看了源码，搞定了，原来是需要输入完整的URL
public String gpt35TurboUrl = "https://api.openai.com/v1/chat/completions";
