### ISSUE TITLE
使用chatgpt时，当返回的内容太长时会中断；无法使用chatgpt3.5

### ISSUE THREAD

**Issue by amazing-cc** [dromara/ChatGPT#128]
感谢您的工作，在使用时我遇到了以下问题
## 问题1：chatgpt
输入问题得到回复，但还未响应完毕
![image](https://user-images.githubusercontent.com/36853357/226938491-3e0430ec-589a-4681-a7a3-9dfa798609b7.png)
在完成响应前，**自动**停止了响应并且之前响应的内容会直接消失。
![image](https://user-images.githubusercontent.com/36853357/226939114-d0fd69a7-e62d-4521-adeb-1eb2b295289d.png)
应该如何解决？

## 问题2: gpt3.5
正常配置了所有内容，在使用gpt3.5 api时报错
> Response failure, please try again. Error message: { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

## 我的配置
**openai**
![image](https://user-images.githubusercontent.com/36853357/226941365-eae9cdbb-10b6-4b7d-b7a2-1078c2f1bc4d.png)

**chatgpt**
![image](https://user-images.githubusercontent.com/36853357/226941036-87ddcbde-bbb1-4b42-961b-f3128ec72ccd.png)

**gpt3.5**
![image](https://user-images.githubusercontent.com/36853357/226942118-1c6ec37b-1d69-4fa4-bc89-8fe10e893dd9.png)

**Comment by obiscr** [comment]
感谢反馈。

问题1：应该是网络不好，我暂时还没遇到过这种情况，在开启上下文聊天的情况下，您可以尝试让他继续说，看会不会接着生成后面的内容。

问题2：请把模型修改成 gpt-3.5-turbo，应该会正常。之前有过一例反馈，是因为模型导致的这个问题。

**Comment by amazing-cc** [comment]
感谢回复！

问题1：昨天测试时，让他继续说它会接着生成后面的内容。**但最关键的是**，在未完成回复就中断的话之前回复的内容会**消失**，这样我无法查看之前的回复。

![image](https://user-images.githubusercontent.com/36853357/227088540-97c3ca31-2743-49cc-b78d-e964d4931a14.png)

我不确定是否是网络原因，因为在使用网页版gpt时，也会出现类似问题。

问题2：修改之后并不起作用，我尝试过重启pycharm，也无用。

**Comment by amazing-cc** [comment]
感谢回复！

问题1：昨天测试时，让他继续说它会接着生成后面的内容。**但最关键的是**，在未完成回复就中断的话之前回复的内容会**消失**，这样我无法查看之前的回复。

![image](https://user-images.githubusercontent.com/36853357/227088540-97c3ca31-2743-49cc-b78d-e964d4931a14.png)

我不确定是否是网络原因，因为在使用网页版gpt时，也会出现类似问题。

问题2：修改之后并不起作用，我尝试过重启pycharm，也无用。

**Comment by obiscr** [comment]
我感觉这两个都是网络问题。
