### ISSUE TITLE
会话总是会自动到最底部

### ISSUE THREAD

**Issue by amazing-cc** [dromara/ChatGPT#129]
![chatgpt插件反馈](https://user-images.githubusercontent.com/36853357/227876219-7851edee-099d-42ea-87fa-31649bc5ffda.gif)
如图，当我想看历史回复时，我必须一直按住鼠标左键，否则它会自动回到最新会话处。
我认为这不是一个很好的设计。

**Comment by obiscr** [comment]
正在生成内容的时候，会自动滚动最底部。内容生成完毕以后，可以网上滚动。

**Comment by amazing-cc** [comment]
> 正在生成内容的时候，会自动滚动最底部。内容生成完毕以后，可以往上滚动。

并非如此，在我的环境下已经生成完毕也会这样？是不是需要做什么额外的设置？
以下是我的配置
PyCharm 2022.1 (Professional Edition)
Build #PY-221.5080.212, built on April 12, 2022

For educational use only.
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    com.intellij.zh (221.262)
    com.intellij.ideolog (203.0.30.0)
    ru.meanmail.plugin.requirements (2022.4)
    cn.yiiguxing.plugin.translate (3.4.2)
    ChatGPT (2.1.7-203.221)
