### ISSUE TITLE
Getting login issue and not able to create api screen short added

### ISSUE THREAD

**Issue by dipeshsukhia** [dromara/ChatGPT#132]
![image](https://user-images.githubusercontent.com/34036367/227881439-c30d802d-ef98-4c85-9d50-5aeac73210dd.png)
![image](https://user-images.githubusercontent.com/34036367/227881584-e3c40710-2d1c-42a6-96c8-538098dbe763.png)

**Comment by obiscr** [comment]
If you want to enable proxies, you must have a valid proxy address. It looks like you just filled in the proxy host and port, but didn't turn on the appropriate service.

**Comment by obiscr** [comment]
This issue is out of date.
