### ISSUE TITLE
Hope plug-in to support ChatGPT new model gpt-4 and gpt-4-0314

### ISSUE THREAD

**Issue by yufeiyohi** [dromara/ChatGPT#135]
能否让程序支持使用API来调用GPT-4-0314这个模型，当前GPT-3.5-Turbo没有这个选项，或者我手动修改ChatGPTSettingsPlugin.xml能否实现这个功能？

**Comment by yufeiyohi** [comment]
ChatGPT API now supports the GPT-4 model, which named gpt-4 and gpt-4-0314. The calling API method is the same as that of gpt-3.5-turbo, which is through https://api.openai.com/v1/chat/completions. Therefore, it should be easy to modify this plug-in to use the new models.

**Comment by obiscr** [comment]
Thank you very much, I saw the latest model here: https://platform.openai.com/docs/models/gpt-4

In the next version, all 4 models will be supported.

**Comment by obiscr** [comment]
Please ask if your account supports gpt-4. Currently, only accounts that have passed the whitelist audit are allowed to use the gpt-4 model.

**Comment by obiscr** [comment]
What I can say for sure is that when you choose gpt-4, you will definitely follow the gpt-4 model to request.

This is debug info:

![image](https://user-images.githubusercontent.com/28687074/228900252-8ef2b93b-0c6f-4fdc-8c9d-52fbafb07f60.png)

**Comment by obiscr** [comment]
@NargiT After my testing, I found it's other errro, not your problem with gpt-4 error response.
