### ISSUE TITLE
在ChatGPT模式下报错，同相的网络环境在CPT-3.5-Turbo模式正常。如下图。另请问如何配置自己的API呢？

### ISSUE THREAD

**Issue by MeditatorV** [dromara/ChatGPT#137]
在ChatGPT模式下报错，同相的网络环境在CPT-3.5-Turbo模式正常。如下图。
![image](https://user-images.githubusercontent.com/47035563/228241527-64169269-2697-4e63-bd44-6d294ac9d8ea.png)
![image](https://user-images.githubusercontent.com/47035563/228241906-7d1ab632-ed43-4122-bc4a-e08d7c80ac08.png)

因为网络环境的原因，直接调用接口的域名api.openai.com被拦截，已经做好了映射的代理API域名：api.test.com，请问如何配置自己的API域名（api.test.com）呢？

**Comment by obiscr** [comment]
目前有两种：

一个是Chat GPT的逆向出来的api
打开，File - Settings/Preference - Tools - OpenAI - ChatGPT，选择Customize，填写自己的域名 （注意，这只是针对非官方的API，官方的API请看下面）

另一个是官方的API：
请参考：https://github.com/dromara/ChatGPT/issues/127#issuecomment-1486214877

**Comment by obiscr** [comment]
至于报错，不知道您是否自定义了URL，用目前插件内置的，应该不会出现这个问题。

**Comment by MeditatorV** [comment]
> 目前有两种：
> 
> 一个是Chat GPT的逆向出来的api 打开，File - Settings/Preference - Tools - OpenAI - ChatGPT，选择Customize，填写自己的域名 （注意，这只是针对非官方的API，官方的API请看下面）
> 
> 另一个是官方的API： 请参考：[#127 (comment)](https://github.com/dromara/ChatGPT/issues/127#issuecomment-1486214877)

我使用的方式是在腾讯云在部署云函数，利用云函数做了api的代理。

**Comment by MeditatorV** [comment]
> 



> 至于报错，不知道您是否自定义了URL（Chat GPT的url），用目前插件内置的，应该不会出现这个问题。

报错是因为把自己利用云函数做了api的代理URL填写到Chat GPT的url的URL里，切换插件内置的就没问题

**Comment by obiscr** [comment]
你可以按照上面的方式，替换完整的url，这应该是可行的

**Comment by gaohan-cmd** [comment]
![image](https://user-images.githubusercontent.com/63499259/228719672-235b3fa6-9fa7-4346-ae97-c24a27e2bba9.png)
![image](https://user-images.githubusercontent.com/63499259/228719721-0118d7d0-61a9-4e28-b014-c89b661ac6b3.png)
请问使用了自定义API，已经在OpenAl Assistant填写了key，结果使用ChatGPT提示未提供key怎么回事？

**Comment by obiscr** [comment]
请参考文档进行设置

**Comment by MeditatorV** [comment]
下图是其他的chatgpt工具设置API秘钥与域名的截图仅供参考，希望在本软件可以替换为自定义API：
![image](https://user-images.githubusercontent.com/47035563/228734210-29f00791-64f2-4767-9022-a766bb4dd4b7.png)
下图是替换为自己的API代理URL的截图：
![image](https://user-images.githubusercontent.com/47035563/228734162-22f461da-9d41-4ff0-a43a-18d4a8694e90.png)

**Comment by obiscr** [comment]
非常感谢，我会尽快支持！

**Comment by obiscr** [comment]
在 [2.1.11版本](https://chatgpt.cn.obiscr.com/release/2.1.11/#131) 已经支持，但是请注意，您必须确保第三方服务器是可信的。对于一些非法的第三方服务器，他们有可能会收集您的API Key。
