### ISSUE TITLE
Change Icon Color

### ISSUE THREAD

**Issue by SebastEnn** [dromara/ChatGPT#139]
The color of the transparent Icon is gray, which results in being not that visible when selected.
Here is the difference:
![grafik](https://user-images.githubusercontent.com/103125747/228460900-a7240f9a-914c-4544-b497-4fc5076cafe2.png)
![grafik](https://user-images.githubusercontent.com/103125747/228460924-bb8c8e38-9be9-414d-98aa-c9eb6c57cb25.png)

**Comment by obiscr** [comment]
Thanks for the feedback, this problem does exist in New UI.

**Comment by obiscr** [comment]
This issue has been fixed in 2.1.10, more details, please see : [release note](https://chatgpt.en.obiscr.com/release/2.1.10/#139)
