### ISSUE TITLE
前缀词界面显示不正常，只有选择时才显示内容，如下图

### ISSUE THREAD

**Issue by MeditatorV** [dromara/ChatGPT#141]
![image](https://user-images.githubusercontent.com/47035563/228735709-0ea53c33-262e-4641-99d2-7758128cd172.png)

**Comment by obiscr** [comment]
感谢反馈，请提供一下：
+ 插件版本
+ ide 版本
+ 复现问题的步骤

或者其他有必要的信息。

**Comment by MeditatorV** [comment]
ide 版本:
![image](https://user-images.githubusercontent.com/47035563/228770811-1a0565bc-e059-481c-9bf4-ac074098bddc.png)
插件版本:2.1.9-203.221
![image](https://user-images.githubusercontent.com/47035563/228771523-beb69f97-81bf-49fa-bc62-7d01b3b50586.png)
复现问题的步骤:
 操作路径：文件--设置--工具--OpenAI--Custom Actions，点击加号，输入中文内容。

**Comment by obiscr** [comment]
我这边完全正常，无法复现

**Comment by obiscr** [comment]
请问有没有什么错误信息，现把问题复现，然后检查下 idea.log，如果有的话，听提供给我，谢谢！

**Comment by MeditatorV** [comment]
不知道如何查看相关的日志，把个日志文件上传
[idea.log](https://github.com/dromara/ChatGPT/files/11117122/idea.log)

**Comment by obiscr** [comment]
非常感谢提供日志，为了但是依然没有看到跟这个问题相关的错误，我这里始终无法复现。

**Comment by obiscr** [comment]
这个问题已经过时，如果能稳定复现，会再次打开。
