### ISSUE TITLE
无法打开Oline ChatGPT,如下图：

### ISSUE THREAD

**Issue by MeditatorV** [dromara/ChatGPT#142]
无法打开Oline ChatGPT,如下图：
已开启全局代理
![image](https://user-images.githubusercontent.com/47035563/228772613-0bfd57a5-6520-47bf-80ae-2a74d9576195.png)
ide 版本:
![image](https://user-images.githubusercontent.com/47035563/228773164-dd8217d4-037c-4b03-ada5-ff4fac979ca8.png)
插件版本:2.1.9-203.221
![image](https://user-images.githubusercontent.com/47035563/228773271-d5d2d7b0-7ad5-43aa-abd2-ab527922574b.png)

复现问题的步骤:

**Comment by obiscr** [comment]
请看一下是否有相关的错误日志。在idea.log里面

**Comment by obiscr** [comment]
这个问题已经过时，如果有最新的进展会再次打开。
