### ISSUE TITLE
可否支持将当前对话导出

### ISSUE THREAD

**Issue by zx-2000** [dromara/ChatGPT#143]
因为token数限制，可能需要将当前的对话记录保存，然后再开启新的对话

**Comment by obiscr** [comment]
我评估了一下，这个功能需要巨大的工作量，因此对于这个功能，可能不会免费。

**Comment by obiscr** [comment]
这个功能会在 [ChatGPTGold](https://chatgpt.gold/) 插件中。ChatGPTGold 目前还在内测阶段，它会很快发布。
