### ISSUE TITLE
建议加入对多个chat的一些支持

### ISSUE THREAD

**Issue by jie97hu** [dromara/ChatGPT#148]
插件很好用！！！针对ChatGPT的多个chat，希望能有以下一些支持

1. 插件的使用过程中会产生一些默认名称的chat如下图：
![image](https://user-images.githubusercontent.com/29095252/229010228-beb3df6d-052f-4d30-bfde-b37753862582.png)
    希望能支持对当前chat进行命名
2.如果可以展示历史chat的话 并选择 进行对话的话就更好了

**Comment by CrazyBunQnQ** [comment]
同求~哈哈哈哈

**Comment by MeditatorV** [comment]
同求

**Comment by obiscr** [comment]
这个开发量很大，也可以做。我需要花很多时间，不过比较遗憾的是，这个功能可能不会免费，可能会付费使用。

**Comment by CrazyBunQnQ** [comment]
冲鸭！

吳子玄 ***@***.***>于2023年4月3日 周一12:50写道：

**Comment by CrazyBunQnQ** [comment]
> 这个开发量很大，也可以做。我需要花很多时间，不过比较遗憾的是，这个功能可能不会免费，可能会付费使用。

冲鸭！😃

**Comment by obiscr** [comment]
这个功能会在 [ChatGPTGold](https://chatgpt.gold/) 插件中。ChatGPTGold 目前还在内测阶段，它会很快发布。

ChatGPT 和 GPT-3.5-Turbo 都会支持历史对话，以及导出功能。
