### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by Smail-cai** [dromara/ChatGPT#149]
插件的中文乱码怎么处理[](url)

**Comment by Smail-cai** [comment]
![image](https://user-images.githubusercontent.com/129476314/229014917-0557a1c9-4441-416a-a2bb-1403ac9ebc4c.png)

**Comment by jackylvm** [comment]
这个能解决吗

**Comment by obiscr** [comment]
应该是这个问题，https://github.com/dromara/ChatGPT/issues/133 已经修复了

**Comment by Smail-cai** [comment]
是的最新版本已修复了
