### ISSUE TITLE
使用报错Failed to connect to bypass.duti.tech/127.0.0.1:443, please try again.

### ISSUE THREAD

**Issue by Songxc999** [dromara/ChatGPT#150]
Response failure, cause: Failed to connect to bypass.duti.tech/127.0.0.1:443, please try again.

Tips: if proxy is enabled, please check if the proxy server is working.

**Comment by ascheman** [comment]
Having the very same problem, thanks for raising the issue @Songxc999, excerpt from idea.log:

`com.obiscr.chatgpt.ChatGPTHandler - ChatGPT: conversation failure. Url=https://bypass.duti.tech/api/conversation, response=null, errorMessage=bypass.duti.tech: nodename nor servname provided, or not known`

**Comment by 15904962787** [comment]
some problem，since today @Songxc999

**Comment by Data-Designer** [comment]
I have the same obstacles

**Comment by 15904962787** [comment]
@Data-Designer 感觉是插件的服务器有了问题

**Comment by obiscr** [comment]
You are right, it is true that there is a problem with the server.  We recommend using the built-in online chat GPT or using GPT-3.5-Turbo for the time being.

**Comment by Songxc999** [comment]
> You are right, it is true that there is a problem with the server. We recommend using the built-in online chat GPT or using GPT-3.5-Turbo for the time being.

OK,thanks for your reply,wish you fix the problem soon.

**Comment by ascheman** [comment]
> You are right, it is true that there is a problem with the server. We recommend using the built-in online chat GPT or using GPT-3.5-Turbo for the time being.

Can you please link to the related documentation how to switch, @obiscr ?
I just installed the plugin and could not even login (cf. https://github.com/dromara/ChatGPT/issues/150#issuecomment-1491425556).

**Comment by obiscr** [comment]
@ascheman 
There are three tabs in the ChatGPT toolwindow, the Online ChatGPT and GPT-3.5-Turbo shoule be working fine.

**Comment by obiscr** [comment]
If you can't see it, you can click the down arrow on the right to show other Tabs
![image](https://user-images.githubusercontent.com/28687074/229077879-8a91902b-0309-43e0-8534-b4f9005f0ab9.png)

**Comment by oxtime** [comment]
坏了， Tips: if proxy is enabled, please check if the proxy server is working.

**Comment by ascheman** [comment]
> If you can't see it, you can click the down arrow on the right to show other Tabs ![image](https://user-images.githubusercontent.com/28687074/229077879-8a91902b-0309-43e0-8534-b4f9005f0ab9.png)

Both of your tips were helpful, thanks @obiscr - I didn't see the other tabs at first.

**Comment by ascheman** [comment]
> 坏了， Tips: if proxy is enabled, please check if the proxy server is working.

Of course, no proxy in place (as you can see from the pasted error message).

**Comment by ascheman** [comment]
With the latest version (2.1.11-222.231) I now get an SSL handshake error:

```
2023-04-03 12:48:44,388 [  85293] SEVERE - com.obiscr.chatgpt.core.TokenManager - ChatGPT: Refresh access token failed, error = SSLHandshakeException: Received fatal alert: handshake_failure
```

**Comment by obiscr** [comment]
Yes, this problem still exists and I can't find a more stable server.

**Comment by Mutahhar** [comment]
> @ascheman There are three tabs in the ChatGPT toolwindow, the Online ChatGPT and GPT-3.5-Turbo shoule be working fine. ![image](https://user-images.githubusercontent.com/28687074/229077262-23855690-6f42-47c5-a67a-b6b4637856fc.png)

Worked for me as well. Thanks @obiscr 👍

**Comment by obiscr** [comment]
Sorry for the long delay on this issue, as I just couldn't find an available server.

Currently you can update the token manually. please update to version 2.1.13, here is the release notes: https://chatgpt.en.obiscr.com/release/2.1.13
