### ISSUE TITLE
设置快捷键打开窗口后焦点在System Role输入框

### ISSUE THREAD

**Issue by geekerzhou** [dromara/ChatGPT#153]
给键盘操作带来极大的不方便，希望能调整为焦点默认在对话输入框上

**Comment by obiscr** [comment]
感谢反馈，没问题

**Comment by obiscr** [comment]
这个问题在2.1.12版本得到修复，鼠标移动上去会变成可编辑状态，鼠标移除自动设置为不可编辑状态，不会在获得焦点。
