### ISSUE TITLE
wondering if webstorm plugin works directly in code? (and also google login)

### ISSUE THREAD

**Issue by pkellner** [dromara/ChatGPT#157]
First, sorry for the issue, but my thinking is that you say you can't use google login in the doc and I did and it seems to work. I did it by going to this URL https://platform.openai.com/account/api-keys and creating a secret key, then pasting it in your webstorm setup.  I'm not sure what to put in for expirations I left it blank.

Also, does your plugin help in the code window? That is, can I do something like select a bunch of code and then ask chatGPT to simplify it or create new code? I know I can paste it into the chapgpt window, but was wondering if there is anything else I can do.

THanks for doing this plugin

**Comment by obiscr** [comment]
Thanks.

> I did it by going to this URL https://platform.openai.com/account/api-keys and creating a secret key

So far it seems that this about google account login should be for some accounts. All some accounts are normal and some accounts are not.

As for working directly in the code, this is already in the plans for future versions.
