### ISSUE TITLE
官方修改api，现在报错了

### ISSUE THREAD

**Issue by alexyueqi** [dromara/ChatGPT#158]
Refresh grant failed, error: Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.

**Comment by obiscr** [comment]
After my testing, it does.
It should be OpenAI that does the restriction.

**Comment by obiscr** [comment]
There is no fix for this issue at the moment, so if you have a better solution, please let me know.

Officially, the api key has been disabled to view usage.
