### ISSUE TITLE
Response failure, cause: Failed to connect to bypass.duti.tech/127.0.0.1:443, please try again.

### ISSUE THREAD

**Issue by MohammadRaziei** [dromara/ChatGPT#159]
hi I have this issue:

Response failure, cause: Failed to connect to bypass.duti.tech/127.0.0.1:443, please try again.

Tips: if proxy is enabled, please check if the proxy server is working.

But I set no global proxy on my computer

**Comment by senflyboy** [comment]
me too

**Comment by obiscr** [comment]
Indeed, the third party service is not available anymore. Working on a solution.

Also this issue is a duplicate of #150. Stay tuned to #150 for subsequent updates.
