### ISSUE TITLE
报错了Response failure, please try again. Error message: { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }

### ISSUE THREAD

**Issue by 123xian123** [dromara/ChatGPT#160]
报错了Response failure, please try again. Error message: { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }
刷新时报错Refresh grant failed, error: Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.
我的api是在官网创建的，用了半个多月了都没事，余额也是够的

**Comment by 123xian123** [comment]
原来是官方试用的API到期了

**Comment by obiscr** [comment]
是的，这个是额度用完了提示。

**Comment by fuchengxin** [comment]
我也是这个提示，但是在chat官网还能问，就是调用这个api的配额完了，可以理解为 官网是通用的通道，api是账号私人通道吗？

**Comment by obiscr** [comment]
是的，网页版可以用，但是api key不可以，都是这样子的。

**Comment by Wang-L-F** [comment]
那有解决方案吗

**Comment by obiscr** [comment]
更换一个新的API Key即可。
