### ISSUE TITLE
Unable to authenticate with open ai

### ISSUE THREAD

**Issue by wskyjames** [dromara/ChatGPT#163]
Looks really good, but i cannot get it to authenticate. I am using the correct email and password (not gmail oauth). I receive the following. 

```
2023-04-03 12:22:41,776 [ 185261] SEVERE - com.obiscr.chatgpt.core.TokenManager - ChatGPT: Refresh access token failed, error = SSLHandshakeException: Received fatal alert: 
```

I have also gone into the open ai settings and added a secret key that i have generated

**Comment by obiscr** [comment]
This is caused by the unavailability of third-party services. Please see: https://github.com/dromara/ChatGPT/issues/150#issuecomment-1491540958

Also this issue is repeated with #150, please follow the progress at https://github.com/dromara/ChatGPT/issues/150
