### ISSUE TITLE
install plugin form disk  than was build form source

### ISSUE THREAD

**Issue by xiaoran301** [dromara/ChatGPT#167]
Plugin 'ChatGPT' (version '2.1.12-222.231') is not compatible with the current version of the IDE, because it requires build 222.2680.4 or newer but the current build is RD-221.5787.36

**Comment by obiscr** [comment]
Thank for report, can you try this version [2.1.12-203.221](https://plugins.jetbrains.com/plugin/20603-chatgpt/versions/stable/314923)

**Comment by xiaoran301** [comment]
no, i fixed by upgrading rider to Build #RD-223.8836.53, built on March 20, 2023 ~_~

**Comment by obiscr** [comment]
In fact, it already exists: https://github.com/dromara/ChatGPT/blob/main/gradle.properties#L12-L13
