### ISSUE TITLE
GPT-4 context support error

### ISSUE THREAD

**Issue by QPoser** [dromara/ChatGPT#171]
Error message "The model: gpt-4 does not exist" when enabling 'Model: gpt-4' and 'Enable context support' parameter in plugin:

**Response failure, please try again. Error message: { "error": { "message": "The model: `gpt-4` does not exist", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }**

**Comment by obiscr** [comment]
This requires your account to be able to support GPT-4. Currently only whitelisted accounts are able to use gpt-4.

**Comment by QPoser** [comment]
Exactly, but I have gpt-4 and if you turn off the Enable context support parameter, then everything works correctly

**Comment by obiscr** [comment]
Because my personal account has not been whitelisted. So I am not but sure if GPT-4 supports context.

**Comment by QPoser** [comment]
Can I help you by passing the API key with GPT-4?

**Comment by obiscr** [comment]
Thank you very much if you can, here is my email address: wuzi@obiscr.com

**Comment by QPoser** [comment]
Done
