### ISSUE TITLE
Response does not shown in Goland IDE

### ISSUE THREAD

**Issue by allenyao0702** [dromara/ChatGPT#172]
For some inputs in Goland IDE, the plugin does not show the response, but if I click the copy button, the response is actually copied to the clipboard and can be pasted in text editor.  My Goland is Build #GO-223.8836.56.
<img width="665" alt="Screen Shot 2023-04-05 at 11 50 31 AM" src="https://user-images.githubusercontent.com/11775447/230177545-ab9f30fb-7011-4dab-a751-793fa2aa2631.png">

**Comment by obiscr** [comment]
Is this chatgpt or gpt-3.5-turbo? And please upgrade to the latest version to check if it still exists.

**Comment by obiscr** [comment]
This issue is out of date.
