### ISSUE TITLE
PyCharm中，插件输入栏会抢占输入焦点

### ISSUE THREAD

**Issue by blackh1** [dromara/ChatGPT#182]
当打开插件时，如果PyCharm中触发了输入提示，输入焦点会变到插件中，这时按tab无法自动补全，而且输入任何内容，都会输入到插件的输入栏中。
![image](https://user-images.githubusercontent.com/74771265/230867814-c438d34c-2871-4a4e-b5ea-a4671062251e.png)
如上图，只是输入了一个字母f，然后显示了可以补全的变量，但是这时输入焦点已经转移到右边的插件中了。

**Comment by obiscr** [comment]
很抱歉，这是一个bug，会尽快修复

**Comment by obiscr** [comment]
这个问题很重要，会在下个版本中修复，新版本已经提交审核。
![image](https://user-images.githubusercontent.com/28687074/230941550-c2596b4f-b648-4a35-85b9-3d70f81fe5f8.png)
