### ISSUE TITLE
自定义action可以不使用弹出框吗？希望可以改成另一种的

### ISSUE THREAD

**Issue by Lucien11** [dromara/ChatGPT#185]
类似于下面这种
<img width="606" alt="image" src="https://user-images.githubusercontent.com/22729986/231366158-d927171b-51c5-43f2-93d4-3bfe0d215cf4.png">

现在这种操作起来不太方便
<img width="183" alt="image" src="https://user-images.githubusercontent.com/22729986/231366314-aff44ccf-e550-4576-a4bf-5f280f92ab62.png">

**Comment by obiscr** [comment]
目前自定义只有在添加的时候才会有从弹框，如果是使用的话，可以直接使用快捷键。会直接显示自定义的Popup

**Comment by k99k5** [comment]
> 目前自定义只有在添加的时候才会有从弹框，如果是使用的话，可以直接使用快捷键。会直接显示自定义的Popup

内置的Prompt能修改吗？现在是英文的。。。

**Comment by obiscr** [comment]
可以修改的，添加自定义前缀的时候可以修改，不知道是不是指这个。

自定义前缀就是为了解决这个问题，支持任何语言。

**Comment by k99k5** [comment]
> 可以修改的，添加自定义前缀的时候可以修改，不知道是不是指这个。
> 
> 自定义前缀就是为了解决这个问题，支持任何语言。

我意思是显示的标题 和 实际提交的现在不能不一样）
实际提交过去的prompt可能是一大串，然后Popup哪块就会一大堆。。。

**Comment by obiscr** [comment]
我明白您的意思了。请问您有比较好的解决方案吗？

**Comment by k99k5** [comment]
> 

增加一个显示的名称就好了吧？

**Comment by k99k5** [comment]
> 可以，没问题，会尽快安排。其实我也是这么想的，哈哈

内置的两个希望也可以更改哈哈

**Comment by obiscr** [comment]
内置的因为一些sdk的缘故，可能不支持。

**Comment by software-market** [comment]
版本：2.1.15-222.231

**Comment by software-market** [comment]
版本  2.1.15-222.231
这俩值会不会是写反了，Name显示在菜单中，点击时发送的还是Name。

**Comment by obiscr** [comment]
没有，name就是显示在右键菜单的。

**Comment by software-market** [comment]
@obiscr  菜单：![image](https://user-images.githubusercontent.com/31737411/233516921-d2d6e8dd-ddc9-4812-89cb-3c9079b826cd.png)
实际发送：
![image](https://user-images.githubusercontent.com/31737411/233516979-8d37fda4-4ac5-4d11-bea2-f836d390486e.png)

设置：
![image](https://user-images.githubusercontent.com/31737411/233517022-6d57dfb0-2f53-4e5c-8879-bc123ae669d5.png)

**Comment by Lucien11** [comment]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/22729986/236141200-cf5c373c-5c20-44f9-aba1-2c861eb45040.png">

Prompt还是不能完全自定义

**Comment by Lucien11** [comment]
自动添加的冒号会影响我要求的格式化内容

**Comment by obiscr** [comment]
> 自动添加的冒号会影响我要求的格式化内容

关于这个，你设置的时候可以不要加 ：
