### ISSUE TITLE
GPT 3.5 Turbo Request failure, cause: connect timed out

### ISSUE THREAD

**Issue by ArchGeass** [dromara/ChatGPT#187]
按照教程给 GPT-3.5-Turbo 配置了API key，但使用时反馈 "GPT 3.5 Turbo Request failure, cause: connect timed out"，无法正常使用

**Comment by ArchGeass** [comment]
环境与版本:
IntelliJ IDEA 2021.3.3 (Community Edition)
Build #IC-213.7172.25, built on March 16, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-60-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 3584M
Cores: 12
Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    leetcode-editor (8.1)
    idea.plugin.protoeditor (213.6461.28)
    com.jetbrains.ChooseRuntime (1.2)
    com.intellij.zh (213.370)
    com.huangmb.idea (1.1)
    com.alayouni.ansiHighlight (1.2.4)
    org.asciidoctor.intellij.asciidoc (0.37.52)
    VisualVMLauncher (1.21.211.6085.0)
    String Manipulation (9.5.0)
    PythonCore (213.7172.48)
    IdeaVIM (1.10.3)
    GenerateSerialVersionUID (3.0.3)
    Docker (213.7172.6)
    Dart (213.7433)
    ChatGPT (2.1.14-203.221)
    dev.eltonsandre.intellij.spring.assistant.plugin (2022.1.2)
    MavenRunHelper (4.20.213.3714.1)
    izhangzhihao.rainbow.brackets (6.26)
    org.intellij.scala (2021.3.22)
    cn.yiiguxing.plugin.translate (3.4.2)
    ASM Bytecode Outline (0.3.5)

Kotlin: 213-1.5.10-release-949-IJ7172.25
Current Desktop: ubuntu:GNOME

**Comment by obiscr** [comment]
是不是需要设置代理，请教查一下
