### ISSUE TITLE
It is prompted when authorizing the plug-in, how can I solve it?

### ISSUE THREAD

**Issue by ligkning** [dromara/ChatGPT#188]
Have any of you encountered this kind of error?

Save the Access Token failed, cause: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1558 path $ 

It is prompted when authorizing the plug-in, how can I solve it?

**Comment by ligkning** [comment]
在授权插件时出现的问题，请问各位有遇到过这种问题吗？

**Comment by obiscr** [comment]
This error appears to be an issue with the JSON format. 

The data returned by the connection opened in the second step is a complete JSON format. Please copy all the content to the plugin and click Save.
