### ISSUE TITLE
Bad gateway Error code 502问题

### ISSUE THREAD

**Issue by OwO-WANG** [dromara/ChatGPT#189]
![image](https://user-images.githubusercontent.com/84651737/232280254-eeff570c-5e43-4c78-a724-ffa32819a489.png)
你好！不知道为什么会出现这样的问题，该如何解决呢？之前使用的时候是正常的，今天早上开始就是这样了！

**Comment by afilp** [comment]
Same with me, right now.

**Comment by OwO-WANG** [comment]
i suspect that we can't pass the vaildation of we are not robots😂 but i don't know how to deal with the problem

**Comment by dimasky228** [comment]
same, I tried different proxies and VPNs

**Comment by willaimChen** [comment]
我也是,之前用的好好的.

**Comment by wooter-s** [comment]
same problem

**Comment by k99k5** [comment]
bypass.churchless.tech
Host
Error

**Comment by mikenthiwa** [comment]
Same problem as well.

**Comment by fqiaoming** [comment]
Same problem as well.

**Comment by heiyl** [comment]
Same problem as well.

**Comment by w1946171541** [comment]
Same problem as well.

**Comment by obiscr** [comment]
Thank you all report this problem. 

 I am currently working on it. It will take some time. 

Please temporarily use Online ChatGPT or GPT 3.5 Turbo.

**Comment by ascheman** [comment]
I do have the very same error.

**Comment by obiscr** [comment]
Please update to 2.1.15 version, this issue had been fixed.

**Comment by q1152928873** [comment]
GPT 3.5 Turbo目前可以使用但长回答会报错

**Comment by obiscr** [comment]
> GPT 3.5 Turbo目前可以使用但长回答会报错

请问有相关的截图或者日志吗？

**Comment by q1152928873** [comment]
开发者你好，在提出问题后，chatgpt会逐字逐句返回答案，当返回内容过多，返回时间就会变长，当答案返回超过30秒的时候，答案就直接变成Request failure了，系统配置如下，代理用的是极光，日本节点





&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月21日(星期五) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/ChatGPT] Bad gateway Error code 502问题 (Issue #189)





  
GPT 3.5 Turbo目前可以使用但长回答会报错
  
请问有相关的截图或者日志吗？

**Comment by obiscr** [comment]
这应该是读取超时了。请适当的调整超时时间。https://chatgpt.obiscr.com/zh/settings/openai-settings/#_1
