### ISSUE TITLE
【优化】开启上下文之后，应该也要把chatgpt答复的内容包含进去。

### ISSUE THREAD

**Issue by 0000005** [dromara/ChatGPT#191]
开启上下文之后，应该也要把chatgpt答复的内容包含进去。不然在很多情况下对话的会很不连贯。因为很多场景下，我们是基于chatgpt的答复进行下一步的提问的。
![image](https://user-images.githubusercontent.com/9690089/232646067-ae366ce7-14c0-4438-8b09-ed75079604b8.png)

**Comment by obiscr** [comment]
这是一个bug，在新版本已经修复了，会尽快分布。
