### ISSUE TITLE
【优化】期望在custom actions 中加一个 title 列

### ISSUE THREAD

**Issue by 0000005** [dromara/ChatGPT#193]
新增一个title列，可以为每一个prompt 命名，这样选择prompt的时候，就可以简单一些。不然感觉选择custom actions的时候，烟花缭乱的。

**Comment by obiscr** [comment]
感谢反馈，这个和 https://github.com/dromara/ChatGPT/issues/185 是重复的。已经计划处理了。后续的更新进展请关注 https://github.com/dromara/ChatGPT/issues/185
