### ISSUE TITLE
【建议】custom actions 中预置一些prompt

### ISSUE THREAD

**Issue by 0000005** [dromara/ChatGPT#194]
可以再custom actions 中预置一些已经优化好的 常用的 prompt，比如 生成单元测试、给代码加注释、逐行解释代码等等。

**Comment by obiscr** [comment]
因为自定义的Prompt比较灵活，完全开放给了用户。右键菜单的显示位置资源比较珍贵。如果插件占用太多的UI显示的资源会不太好。因此如果您需要其他的指令，还是建议您使用自定义的Prompt。可以很方便的使用 `Ctrl + Q` 的快捷键调用出来。

还有一个原因是，插件面向的是所有的IDE。所有的编程语言，上述的一些prompt可能只是针对某种特定的场景或者编程语言。通用性方面也不是很好。因此在后面的一次更新中，只保留了最常用的一些 Prompt。

还请理解。感谢！
