### ISSUE TITLE
Error code 523

### ISSUE THREAD

**Issue by constu** [dromara/ChatGPT#195]
![mmexport1681624279260](https://user-images.githubusercontent.com/115908156/232658550-a5df943c-3d58-490c-82fb-fd0c8236fb94.png)
我无法正常使用任何插件功能，我是否应该使用vpn代理，使用vpn代理应该进行什么配置？

**Comment by obiscr** [comment]
这个问题可以归类到 https://github.com/dromara/ChatGPT/issues/189，虽然错误码不一样，但是本质上还是同一类问题。后续的进展，请关注 https://github.com/dromara/ChatGPT/issues/189。
