### ISSUE TITLE
反代挂了？

### ISSUE THREAD

**Issue by hubumulity** [dromara/ChatGPT#196]
Response failure, please try again. Error message:
bypass.churchless.tech | 502: Bad gateway

Bad gateway Error code 502
Visit cloudflare.com for more information.
2023-04-18 06:31:47 UTC

You
BrowserWorking

Hong Kong
Cloudflare Working

bypass.churchless.tech
HostError

What happened?
The web server reported a bad gateway error.

What can I do?
Please try again in a few minutes.

Cloudflare Ray ID: 7b9adde55a710f0c • Your IP: Click to reveal 43.198.25.96 • Performance & security by Cloudflare

**Comment by obiscr** [comment]
是的，正在修复。
