### ISSUE TITLE
Response failure, cause: Invalid content-type: application/octet-stream, please try again.

### ISSUE THREAD

**Issue by JingwenLi** [dromara/ChatGPT#198]
![image](https://user-images.githubusercontent.com/20828375/232945341-9d53b76a-a6f4-4230-a660-963554c63996.png)

**Comment by deeponder** [comment]
+1

**Comment by hubumulity** [comment]
+1

**Comment by wuhua111** [comment]
+1

**Comment by zhangjiepro** [comment]
+10086

**Comment by obiscr** [comment]
This issue will be fixed in next version, the next version is in preview.

**Comment by obiscr** [comment]
Please update to 2.1.15 version, this issue had been fixed.
