### ISSUE TITLE
[feature] Increase input size

### ISSUE THREAD

**Issue by akkonrad** [dromara/ChatGPT#199]
Please increase input size, it barely fits 3 lines, it could be resizable or at least configurable in settings, bigger input would be very useful when editing code for example and reviewing content before sending

**Comment by obiscr** [comment]
Thanks for the feedback, you can actually drag the size of the input text area manually. The top border of the text area can be dragged.

**Comment by akkonrad** [comment]
Sorry I had to miss it, I tried so many times 😂😂

czw., 20 kwi 2023, 20:24 użytkownik 吳子玄 ***@***.***> napisał:
