### ISSUE TITLE
🙏为什么Online ChatGPT的页面是白屏

### ISSUE THREAD

**Issue by DumKing** [dromara/ChatGPT#202]
![image](https://user-images.githubusercontent.com/41665000/233827876-27e1dea1-789b-4be3-b9b7-0632cac5f55e.png)
如图。我的页面打开就是白屏, 我用的idea的新UI， ChatGPT tab好用， Online ChatGPT白屏
idea: 223.7571.182
ChatGPT (2.1.16-222.231)
🙏🙏

**Comment by Bofuser** [comment]
好像要科学上网才能打开

**Comment by DumKing** [comment]
> 好像要科学上网才能打开

肯定是能科学上网的，这一点不用怀疑，毕竟ChatGPT都能用，只有OnlineChatGPT不能用

**Comment by obiscr** [comment]
能否尝试点击Online ChatGPT 菜单栏的 X 清理 Cookies ，然后再点击刷新按钮刷新一下。

**Comment by DumKing** [comment]
> 能否尝试点击Online ChatGPT 菜单栏的 X 清理 Cookies ，然后再点击刷新按钮刷新一下。

白屏已经好了，我清理了idea和所有缓存，终于好使了，但是又出现了新的问题
![image](https://user-images.githubusercontent.com/41665000/234166990-1116aa0d-47da-40f0-bc94-6c02482bd3dd.png)
Google不允许用这个浏览器登录

**Comment by obiscr** [comment]
这个的话，有可能是OpenAI官方的限制，也有可能跟账号有关系。也有可能是ip的问题。

**Comment by DumKing** [comment]
> 这个的话，有可能是OpenAI官方的限制，也有可能跟账号有关系。也有可能是ip的问题。

大家都没有遇到限制用这个浏览器登录的问题吗

**Comment by ruiizhi792** [comment]
我也遇到了这个问题,切换浏览器和更换成无痕模式都可以解决白屏问题,但是我没有遇到弹窗显示浏览器不安全的情况

**Comment by obiscr** [comment]
A proxy server may be required to access. Alternatively, you can try clearing cookies.
