### ISSUE TITLE
作者是否考虑开发保留多个聊天的功能？

### ISSUE THREAD

**Issue by cccdl** [dromara/ChatGPT#205]
现在版本好像无法查看历史对话，可否考虑后续版本加入此功能

**Comment by obiscr** [comment]
多个聊天的功能已经在 [ChatGPTGold](https://plugins.jetbrains.com/plugin/21558-chatgptgold) 插件中得到了支持，您可以查看这里的介绍：[ChatGPTGold-has-been-released](https://chatgpt.gold/zh/blog/posts/2023/ChatGPTGold-has-been-released/)
