### ISSUE TITLE
Response failure, please try again. Error message: {"detail":{"message":"Unauthorized - Invalid access token"}}

### ISSUE THREAD

**Issue by yulin011** [dromara/ChatGPT#214]
![image](https://user-images.githubusercontent.com/87841321/235365740-99ce931d-d5f4-4248-8938-113075d223a6.png)
请问这种问题怎么解决呀，我也已经配置好了apikey，也打开了clash的代理翻墙

**Comment by obiscr** [comment]
token过期了，请重新配置您的access token

**Comment by yulin011** [comment]
没有呀我是昨天刚申请的token，不可能那么快过期

**Comment by obiscr** [comment]
这是openai服务器返回的消息。但是根据返回的消息来看，确实如此。您可重新获取一下token。对比一下看是否有变化。如果不一样。那就说明token确实刷新了。

**Comment by lfk985** [comment]
https://chat.openai.com/api/auth/session,  配置您的access token，是指的配置“这个get请求时，浏览器窗口返回的accessToken”  ,而不是配置apikey

**Comment by obiscr** [comment]
对，api key是 GPT-35-Turbo Tab的，chatgpt Tab需要的是access token。
