### ISSUE TITLE
Your authentication token has expired. Please try signing in again

### ISSUE THREAD

**Issue by zjz2009000** [dromara/ChatGPT#216]
![image](https://user-images.githubusercontent.com/20659728/236104283-773d988f-d6f7-4723-bdf3-294a4022fda4.png)
![image](https://user-images.githubusercontent.com/20659728/236104422-3f7a8f04-1891-44f4-9862-45c87e1d5f83.png)
Return the token expired parameter, but the token I configured is within the expiration date. What should I do?

**Comment by obiscr** [comment]
Based on recent feedback, it appears that OpenAI has adjusted the timing of access token expiration. However, the Expiration time returned by the api is not accurate.

Solution: Retrieve the access token in the browser (click the **Get Token** button)
