### ISSUE TITLE
no formatting

### ISSUE THREAD

**Issue by pilot114** [dromara/ChatGPT#36]
answer from chatGPT may contain formatted code

![image](https://user-images.githubusercontent.com/3529238/211666819-8e0e593c-d731-4604-b199-ffd22d1bbcd2.png)

in online pretty view with button "copy code"
![image](https://user-images.githubusercontent.com/3529238/211667412-4c68fe28-cb67-48a4-9379-93f65e00efc5.png)

**Comment by pilot114** [comment]
its latest PhpShtorm

**Comment by obiscr** [comment]
Thanks for the feedback. Currently, the plug-in is connected to an old model called GPT3, and the data it returns is not in the markdown format. The web version is ChatGPT, which is the latest AI model, and the returned content is in standard markdown format. So there will be differences.

As for whether the GPT3 display copy button will be supported in the plugin, it is temporarily uncertain.

**Comment by obiscr** [comment]
At present, the latest version of the plug -in format should be fine, but there is no highlight. Please update to the latest version.
