### ISSUE TITLE
webstorm下报http响应码400 已经按文档配置过-Dfile.encoding=UTF-8

### ISSUE THREAD

**Issue by Nxir** [dromara/ChatGPT#55]
根据[文档](https://docs.obiscr.com/article/GPT-QA)修改了三个文件 重启了 依然报400

<img width="786" alt="image" src="https://user-images.githubusercontent.com/5908020/218127274-48fa7b26-78fb-4911-aa43-9386bed9bf0e.png">
<img width="484" alt="image" src="https://user-images.githubusercontent.com/5908020/218127644-86badded-215c-46a9-a1a7-bc943c808d29.png">

环境如下:
m1芯片mac
webstorm 2022.3.2
插件版本2.0.2-222.223 使用官方源并配置秘钥

**Comment by obiscr** [comment]
请问使用的是什么源环境？官方源吗？另外也请提供一下您的插件版本，ide版本等信息。

**Comment by obiscr** [comment]
感谢反馈，我会尽快处理。

**Comment by obiscr** [comment]
我这边暂时没有发现，请您更换秘钥或者升级到最新版之后看下是否还有这个问题，有的话，及时跟我反馈。谢谢！

**Comment by obiscr** [comment]
插件迎来一次大更新，请更新到最新版看是否有问题。这个issue暂时关闭了。后期如果还是不能用。我会再次打开它。
