### ISSUE TITLE
Please provide more details:IDE version: #IU-223.8214.52 -  IntelliJ IDEA 2022.3.1 (Ultimate Edition maven3

### ISSUE THREAD

**Issue by 1771063934** [dromara/ChatGPT#72]
Please provide more details:
IDE version：?
Plugin version：?

_Originally posted by @obiscr in https://github.com/obiscr/ChatGPT/issues/71#issuecomment-1439489728_

**Comment by obiscr** [comment]
Please see if there is still this problem after updating to the latest version. If so, I will open it again.
