### ISSUE TITLE
Too many request

### ISSUE THREAD

**Issue by vanchuong201** [dromara/ChatGPT#73]
I got an error.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/7368585/220862696-a064cc3e-d364-47ed-96b5-9d9d75eb4364.png">
Please show me how to fix it.

**Comment by pjmartorell** [comment]
I have the same issue

**Comment by obiscr** [comment]
This information is returned by OpenAI's server, which should be caused by too many users and server overload.

**Comment by obiscr** [comment]
The latest version of the plugin uses GPT 3.5 Turbo This is the official server. This problem should not appear again.
Please upgrade to latest vesion.
