### ISSUE TITLE
感觉不是在一个上下文聊天的呢？

### ISSUE THREAD

**Issue by lowking** [dromara/ChatGPT#76]
这上下文回答对不上🤣前面问他python的问题，后面回答java的。最后莫名其妙回答计算园的面积
![image](https://user-images.githubusercontent.com/33308659/221098965-991e0c15-7da8-4a31-b87f-979017b4e4f8.png)

**Comment by obiscr** [comment]
对，现在的gpt3可能会有这种情况，等chatgpt的  api 开放了。会尽快接入。

**Comment by obiscr** [comment]
目前最新的模型 GPT 3.5 Turbo 已经接入。请更新到最新版查看是否还有此问题。

**Comment by obiscr** [comment]
Please see : https://github.com/dromara/ChatGPT/issues/81
