### ISSUE TITLE
SSLHandshakeException: Remote host terminated the handshake

### ISSUE THREAD

**Issue by naah69** [dromara/ChatGPT#82]
curl调用api可以运行，但是插件不行
<img width="585" alt="image" src="https://user-images.githubusercontent.com/25682169/222877059-adbdbb69-a7dc-4fd7-a0cc-208d5c7b2065.png">

**Comment by naah69** [comment]
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/25682169/222877080-34e63b37-9a70-4308-99e6-52963871f8f4.png">

**Comment by obiscr** [comment]
请问您是否开启了代理？如果开启的话，请在插件内也配置一下。参考这个 issue：https://github.com/dromara/ChatGPT/issues/81

**Comment by obiscr** [comment]
这个issus暂时关闭了，如果后期有需要，会再次打开。
