### ISSUE TITLE
希望 Turbo 接口能加入联系上下文进行对话的功能和选项

### ISSUE THREAD

**Issue by CrazyBunQnQ** [dromara/ChatGPT#85]
原生网页版能够联系上下文进行对话，但是 Turbo 接口不行(如图)，希望能添加以下功能

- [ ] 启用上下文(会消耗更多的余额)
- [ ] 显示消费金额 

![ChatGPT](https://user-images.githubusercontent.com/17765748/222922481-2eac415a-ee5e-4672-b0e9-6487a6ef718b.png)
![Turbo](https://user-images.githubusercontent.com/17765748/222922499-7f9b7aa7-7e8d-4217-85c2-1a2f47f162b6.png)

### 上下文参考

![上下文](https://user-images.githubusercontent.com/17765748/222922827-b257fc93-af4b-41ab-a00b-ee9fcf740f30.png)

**Comment by obiscr** [comment]
感谢反馈，后续会考虑添加。。顺便问一下，这几个分别代表什么，你知道吗？
```
role : "system", 
role : "user", 
role : "assistant", 
```

**Comment by CrazyBunQnQ** [comment]
> 感谢反馈，后续会考虑添加。顺便问一下，这几个分别代表什么，你知道吗？
> 
> ```
> role : "system", 
> role : "user", 
> role : "assistant", 
> ```

我理解 `assistant` 代表机器人，`user` 代表用户，但是 `system` 不太清楚，看起来像是这个对话的标题，就是原生页面上完成一个新对话之后系统自动给对话的命名，像是给这个助手的一个大致定义

**Comment by obiscr** [comment]
> > 感谢反馈，后续会考虑添加。顺便问一下，这几个分别代表什么，你知道吗？
> > ```
> > role : "system", 
> > role : "user", 
> > role : "assistant", 
> > ```
> 
> 我理解 `assistant` 代表机器人，`user` 代表用户，但是 `system` 不太清楚，看起来像是这个对话的标题，就是原生页面上完成一个新对话之后系统自动给对话的命名，像是给这个助手的一个大致定义

好的，非常感谢！

**Comment by obiscr** [comment]
那这个如果支持的话，是不是需要把之前的历史对话都带过去。

**Comment by CrazyBunQnQ** [comment]
> 那这个如果支持的话，是不是需要把之前的历史对话都带过去。 @CrazyBunQnQ

是的，不过应该有上限，以前 API 的 tokens 上限好像是 2000 个，新的没细看，估计也差不多

**Comment by obiscr** [comment]
好的，我调试一下

**Comment by CrazyBunQnQ** [comment]
在原生页面上用的时候，发现 Plus 用的不一样的模型，希望还能加个选项

- [ ] 是否 Plus

模型名称 `text-davinci-002-render-paid`，这个看起来应该好实现一些~

![1678116467212](https://user-images.githubusercontent.com/17765748/223155732-1e08e102-5bb3-40f5-a66f-93ce14231574.jpg)

**Comment by h7ml** [comment]
> 

role: "system" 表示系统或者机器人在对话中的身份，通常是用来执行系统任务或者提供基本的服务和信息。
role: "user" 表示对话中的用户或者客户，通常是提出问题或者需求，系统或者助手会回答或者执行相关任务。
role: "assistant" 表示对话中的助手或者辅助者，通常是用来提供更加智能化的服务，如语言理解、推荐、建议等。

**Comment by obiscr** [comment]
@h7ml 非常感谢！

**Comment by CrazyBunQnQ** [comment]
> @CrazyBunQnQ 谢谢建议，目前最新的2.1.2版本，已经已经支持了在线ChatGPT，里面如果是plus的话，可以直接登录，使用plus的模型。所以这个功能待定。我想暂时看下用户反馈。

嗯嗯 好滴

**Comment by h7ml** [comment]
> 请问有没有一个标准去判断什么时候应该用那种 role？

![image](https://user-images.githubusercontent.com/55233292/223346850-7b82a32e-590e-4f17-a1a5-5435ecbfc71a.png)

可以参考下他自己的回答。

**Comment by obiscr** [comment]
谢谢！

**Comment by obiscr** [comment]
这个功能将会在2.1.4版本得到支持。
