### ISSUE TITLE
[Bug] in chatGPT plug-in components，No response to questions.

### ISSUE THREAD

**Issue by speaker5432111** [dromara/ChatGPT#91]
**Describe the bug**
in chatGPT plug-in components，No response to questions.

**To Reproduce**
1. seting
2. openAI
3. Proxy Settings
4. HPPT>127.0.0.1>6942
5. CHATGPT>Offical>login
6. See error   login failed!

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/109707270/223110097-7f671ef2-7249-443f-9802-2fb49856945c.png)
![图片](https://user-images.githubusercontent.com/109707270/223111013-b7ac9cda-3309-4da2-9b1f-995903820717.png)
![图片](https://user-images.githubusercontent.com/109707270/223111138-98ff8c4d-a82d-4302-9d69-b6d420d3621e.png)

**Environment (please complete the following information):**
PyCharm 2022.2.3
2.1.1-222.223

**Additional context**

**Comment by obiscr** [comment]
About ChatGPT：The ChatGPT window cannot be used without successful login (no access token obtained).

About GPT-3.5-Turbo：Can you provide the idea.log?

**Comment by speaker5432111** [comment]
![图片](https://user-images.githubusercontent.com/109707270/223117306-cc66e04a-a200-4a26-99b3-1f9d8814507b.png)
![图片](https://user-images.githubusercontent.com/109707270/223117386-0d728767-5122-4646-9513-57ff374c5750.png)
问问题没有回复，我的UTF-8也是按视频改的

**Comment by obiscr** [comment]
请提供一下idea.log

**Comment by obiscr** [comment]
不知道您的问题解决了没，这个issue暂时关闭了，后期如果有需要会再次打开。
