### ISSUE TITLE
[Bug]ConnectException: Connection timed out: connect

### ISSUE THREAD

**Issue by q120379739** [dromara/ChatGPT#92]
**Describe the bug**
用postman调得通https://api.openai.com/v1/chat/completions，但是在IDEA一直提示连接超时

**Screenshots**
![image](https://user-images.githubusercontent.com/54164039/223296305-f5233cb8-4141-4bc2-bef9-95c390a8b68b.png)

**Environment (please complete the following information):**
 - IDE Version [IntelliJ IDEA 2020.3.4 x64]
 - Plugin Version [e.g. 2.1.2-203.221]

**Comment by obiscr** [comment]
应该是这个问题，请参考这个进行设置：https://github.com/dromara/ChatGPT/issues/81

**Comment by q120379739** [comment]
确实是代理问题，设置完就可以了，感谢！
