### ISSUE TITLE
[Bug]已经更新了2.1.2，但是online版本还是不能登陆，提示浏览器不安全

### ISSUE THREAD

**Issue by Geek-monk** [dromara/ChatGPT#95]
![image](https://user-images.githubusercontent.com/43717530/223352439-feb35bf1-5187-4ccc-88a1-f9cb1045a75a.png)

**Comment by Stephen-kt** [comment]
I have this problem too. SomeBody helps?

**Comment by obiscr** [comment]
Sorry, OpenAI does not officially support Google/Microsoft account login. The temporary solution is: only other common email accounts can be used
