### ISSUE TITLE
[Bug] Can not log in to my OpenAI account through ChatGPT module in Pycharm.

### ISSUE THREAD

**Issue by honzazarcky** [dromara/ChatGPT#96]
**Describe the bug**
When I try to log into my account in OpenAI through Pycharm as it described here: https://chatgpt.en.obiscr.com/settings/ , I can not do it. It always says the same:

Login failed!

Refresh access token failed, please try it later. Please check idea.log for more details.

I tried like 50 times and it still says the same.

Posted this in the review page if the plugin and was told to create this bug ticket. I already set up the proxy as is described on the page above.

**To Reproduce**

Do not know.

**Expected behavior**
I should be able to log in and the access token should be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/78302836/223355362-018e96a6-d10b-4db2-8bfe-2ac10d208f2d.png)

**Environment (please complete the following information):**
- IDE version - Pycharm 2022.3.2
 - ChatGPT 2.1.2-202

**Comment by obiscr** [comment]
From my experience, this should be where the configuration is wrong. Most likely it's a proxy.

**Comment by honzazarcky** [comment]
I set the proxy exactly as you showed in the settings page. Am I missing something?

**Comment by obiscr** [comment]
Could you provide the idea.log? Maybe I can get some useful information.

**Comment by erickczh** [comment]
I encountered the same issue and conducted additional troubleshooting steps to assist in identifying the problem. Firstly, I attempted to log in using my OpenAI username and password, but received an error message indicating that the access token could not be refreshed. I checked the logs and found that the error was "Get access token failed."

Next, I visited https://chat.openai.com/api/auth/session to manually obtain my access token and applied it to the token session. However, I received an "Access denied" error message with an error code of 1020, which suggests that the site owner may have set restrictions that prevented me from accessing the site.

After researching the issue further, I found that the most likely cause is related to Cloudflare's firewall rules. For more information, refer to https://support.cloudflare.com/hc/en-us/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error1020.

idea.log:
`2023-03-08 11:03:27,995 [  24491] SEVERE - com.obiscr.chatgpt.core.TokenManager - ChatGPT: Refresh access token failed, error = Get access token failed. Please try again later.
2023-03-08 11:03:32,570 [  29066] SEVERE - com.obiscr.chatgpt.core.TokenManager - ChatGPT: Refresh access token failed, error = Get access token failed. Please try again later.
`

error message from API calls:
`Access denied
Error code 1020
You do not have access to chatgpt.duti.tech.
The site owner may have set restrictions that prevent you from accessing the site.
 Error details
 Provide the site owner this information.
 I got an error when visiting chatgpt.duti.tech/api/conversation.
Error code: 1020
Ray ID: 7a4a9b054c2f9a0b
Country: US
Data center: fra03
IP: [redacted]
Timestamp: 2023-03-08 11:05:52 UTC
Click to copy
 Was this page helpful?  Yes   No 
Thank you for your feedback!
Performance & security by Cloudflare`

**Comment by obiscr** [comment]
Well, this is because the third-party server. I am the same situation at this moment.

**Comment by obiscr** [comment]
The temporary alternative is to use Online ChatGPT, which also supports built-in commands for the right mouse button.
