### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Liukang1002** [dromara/ChatGPT#97]
**Describe the bug**
代理能登录且获取sessionid，聊天不行

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/74349836/223457240-934f339c-0afc-4397-acad-ede14a88d48e.png)

**Environment (please complete the following information):**
 - IDE Version [e.g. PyCharm 2022.3.1]
 - Plugin Version [e.g. 2.1.1-222.223]
**Additional context**

**Comment by obiscr** [comment]
这是第三方服务器问题，只能等他修复。

**Comment by Liukang1002** [comment]
> 这是第三方服务器问题，只能等他修复。
谢谢！

**Comment by Liukang1002** [comment]
> 这是第三方服务器问题，只能等他修复。

请问三方依赖的版本有升级到最新嘛

**Comment by obiscr** [comment]
目前已经是最新的版本
